using System;
using System.ComponentModel.DataAnnotations;

namespace E_commerce.Dto.UserDtos;

public class ResetPasswordDto
{
    // The ID of the user for whom the password is being reset
    [Required(ErrorMessage = "User ID is required.")]
    public required int UserId { get; set; }

    // The token required to reset the password, generated by the system
    [Required(ErrorMessage = "Password reset token is required.")]
    public required string Token { get; set; }

    // The new password to set, must be at least 6 characters
    [Required(ErrorMessage = "New password is required.")]
    [StringLength(255, MinimumLength = 6, ErrorMessage = "Password must be at least 6 characters.")]
    public required string NewPassword { get; set; }

}

